version: "3"
services:
  casdoor:
    image: nzhinuconnect
    container_name: casdoor
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${HOST}
      DB_PORT: ${PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - casdoor_data:/var/lib/casdoor
    depends_on:
      - db
    networks:
      - app_network


  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - app_network


  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    container_name: django_todo_app
    volumes:
      - web_data:/app 
      - ./locale:/app/locale
    environment:
      CASDOOR_CLIENT_ID: ${CASDOOR_CLIENT_ID}
      CASDOOR_CLIENT_SECRET: ${CASDOOR_CLIENT_SECRET}
      CASDOOR_REDIRECT_URI: ${CASDOOR_REDIRECT_URI}
      CASDOOR_AUTHORIZATION_ENDPOINT: ${CASDOOR_AUTHORIZATION_ENDPOINT}
      CASDOOR_TOKEN_ENDPOINT: ${CASDOOR_TOKEN_ENDPOINT}
      CASDOOR_USERINFO_ENDPOINT: ${CASDOOR_USERINFO_ENDPOINT}
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - 3000:3000
    depends_on:
      - web
    environment:
      # - REACT_APP_API_HOST=${REACT_APP_API_HOST}
      - REACT_APP_API_PORT=${REACT_APP_API_PORT} 
    volumes:
      - react_data:/app/frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  casdoor_data:
  web_data:
  my_db:
  react_data:
