'''
Django settings for todo_app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
'''

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6*hhxkqt)m$y(ir@fic5-d13mbp56-+nag_$no9t&m1190#zi6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Languages

LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Application definition
INSTALLED_APPS = [
    'taskapp',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_swagger',
    'corsheaders',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

ROOT_URLCONF = 'todo_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'todo_app'),
        'USER': os.getenv('MYSQL_USER', 'mael'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'grace'),
        'HOST': os.getenv('HOST', 'db'),
        'PORT': os.getenv('PORT', '3306'),
    }
}

APPEND_SLASH=False

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# auto logout
AUTO_LOGOUT = {
    'SESSION_TIME': 1000, #15s after the last login
    'IDLE_TIME': 600, #10mins of downtime(no request)
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
# ]

CORS_ORIGIN_ALLOW_ALL = True

REDIRECT_URI = 'http://127.0.0.1:8001/callback/'

LOGIN_REDIRECT_URL = 'http://127.0.0.1:8001/callback/'

LOGIN_URL = '/login/'

AUTH_USER_MODEL='taskapp.CustomUser'

CASDOOR_CLIENT_ID = os.getenv('CASDOOR_CLIENT_ID')
CASDOOR_CLIENT_SECRET = os.getenv('CASDOOR_CLIENT_SECRET')
CASDOOR_REDIRECT_URI = os.getenv('CASDOOR_REDIRECT_URI')
CASDOOR_AUTHORIZATION_ENDPOINT = os.getenv('CASDOOR_AUTHORIZATION_ENDPOINT')
CASDOOR_TOKEN_ENDPOINT = os.getenv('CASDOOR_TOKEN_ENDPOINT')
CASDOOR_USERINFO_ENDPOINT = os.getenv('CASDOOR_USERINFO_ENDPOINT')


CASDOOR_CONFIG = {
    'endpoint': 'http://172.19.0.4:8000/',
    'client_id': 'a87722a6ca745792e21a' , 
    'client_secret': 'a4db06b2b38c451142efbbfd9ba50387754f1985',
    'redirect_uri': 'http://127.0.0.1:8001/callback/',
    'authorization_endpoint': 'http://172.19.0.4:8000/login/oauth/authorize',
    'token_endpoint': 'http://172.19.0.4:8000/api/login/oauth/access_token',
    'userinfo_endpoint': 'http://172.19.0.4:8000/api/userinfo'
}



